---
name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: |
        go build ./...

    - name: Test
      run: |
        go vet ./...

        go get github.com/gordonklaus/ineffassign
        ineffassign ./...
        
        go get golang.org/x/lint/golint
        golint ./...
        
        go get github.com/client9/misspell/cmd/misspell
        find . -type f | xargs misspell -source=text -error
        
        go get honnef.co/go/tools/cmd/staticcheck
        staticcheck ./...
        
        go get github.com/onsi/ginkgo/ginkgo github.com/onsi/gomega/...
        ginkgo -r -randomizeAllSpecs -randomizeSuites -failOnPending -nodes=1 -compilers=1 -race -trace -cover
